### ISSUE TITLE
Don't show tab bar in browser window

### ISSUE THREAD

**Issue by stweil** [UB-Mannheim/PalMA#114]
Currently the Midori browser shows a tab bar above the web page.

As the tab has no useful function for our application, but takes space, it should be suppressed. A possible solution might be calling `/usr/bin/midori -e show-navigationbar=false -a URL`.

**Comment by dennmuel** [comment]
We tried your suggestion without success back in the new-browser-branch as well as just now. Have you tested this command? If so, please offer a working example.
Please note the used [midori config](https://github.com/UB-Mannheim/PalMA/blob/palma-redesign/settings/midori/config), where we tried to hide all control elements. Maybe there is an option we overlooked. Feel free to add further options.
Also `-e show-navigationbar=false` doesn't look like it would change anything, because the navigation bar is already hidden.

**Comment by stweil** [comment]
The cited example works without any Midori config file. You can disable the navigation bar either on the command line or in a config file. In your case, it was already disabled by the config file, so the command line option does not change anything. If you run without a config file, you need that command line option.

**Comment by dennmuel** [comment]
We tried just as you suggested yesterday, too, also with no success. If you can contribute a working example you can contribute your solution to a testing branch and if it works better than the current solution we will implement it after todays rollout.

**Comment by dennmuel** [comment]
Closed: 0d6f3a18563479a9cdd356a7eeaa31053a744a13
