### ISSUE TITLE
Update TRANSLATIONS.md

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/PalMA#44]
https://github.com/UB-Mannheim/PalMA/blob/master/TRANSLATIONS.md

**Comment by stweil** [comment]
Done.

**Comment by zuphilip** [comment]
Okay, but does the script work correctly?

* Why are there so many contributors in the new `zh-tw`?
* Why is German still incomplete?
* Why is Alex a contributor now for all languages?

**Comment by stweil** [comment]
I used a modified script (`git log --follow`) because otherwise some contributors were missing (renamed files). The drawback is that all those language files are based on the English one, so anybody who wrote that one is also a contributor of the derived files.

The script claims that the German translation is incomplete because the translation of _PIN_ is _PIN_ and obviously this is not handled correctly.

**Comment by wagneral** [comment]
Still open ... what to do with this?

**Comment by stweil** [comment]
Many texts changed, so this file needs an update to reflect the missing translations. I suggest to keep the issue open until the update was done.

**Comment by wagneral** [comment]
Ok.

**Comment by zuphilip** [comment]
Fixed by 0ad630d2770fe58f5e5be49256938c45fd4eea8a more recent updates

**Comment by stweil** [comment]
Commit 82d2b577271466bea4e418df1e2d09ba8f659dc8 was also important to fix this issue.
