### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by kba** [UB-Mannheim/PalMA#5]

**Comment by wagneral** [comment]
Will this be realized with the responsive UI?

**Comment by dennmuel** [comment]
Since there is no description of what is meant by "touchscreen support" in this issue, I cannot give a clear answer to that. However, you can definitely use the PalMA controls on a smartphone or tablet. The handling for some controls (like the ones that are basically "arrow up" or "arrow down") is still not really smooth, but overall they do their job. Does this answer fit your question or can I help with further information?

**Comment by zuphilip** [comment]
I suggest to make a real-life test with tablets and a PalMA station that is up-to-date.

**Comment by wagneral** [comment]
Ok, seems to work on the named devices. We'll consider it in the upcoming PalMA Redesign development.
